### ISSUE TITLE
Incorrect license header

### ISSUE THREAD

**Issue by triphora** [marcus8448/FabricMods#3]
Your license header looks like this:

> Copyright (C) 2019-2021 marcus8448
>
> This program is free software: you can redistribute it and/or modify
> it under the terms of the GNU General Public License as published by
> the Free Software Foundation, either version 3 of the License, or
> (at your option) any later version.
>
> This program is distributed in the hope that it will be useful,
> but WITHOUT ANY WARRANTY; without even the implied warranty of
> MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
> GNU General Public License for more details.
>
> You should have received a copy of the GNU General Public License
> along with this program.  If not, see <https://www.gnu.org/licenses/>.

However, you use the LGPL-3.0-only, not the GPL-3.0-or-later (rightfully so, the GPL is invalid for MC mods).

The correct license header would look like this:

> Copyright (C) 2019-2021 marcus8448
>
> This program is free software: you can redistribute it and/or modify
> it under the terms of the GNU Lesser General Public License as published by
> the Free Software Foundation, version 3.
>
> This program is distributed in the hope that it will be useful,
> but WITHOUT ANY WARRANTY; without even the implied warranty of
> MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
> GNU Lesser General Public License for more details.
>
> You should have received a copy of the GNU Lesser General Public License
> along with this program.  If not, see <https://www.gnu.org/licenses/>.

**Comment by marcus8448** [comment]
Thanks!
